### ISSUE TITLE
Error on go get

### ISSUE THREAD

**Issue by muka** [citilinkru/libudev#1]
Hi,
great library! I am using go 1.14 and issuing a go get in my project return an error (on linux)

```sh
$ go get github.com/citilinkru/libudev
go: downloading github.com/citilinkru/libudev v0.1.0
go get github.com/citilinkru/libudev: create zip: malformed file path "assets/fixtures/demo_tree/run/udev/data/c13:32": invalid char ':'
```

Do you have a suggestion?

Thanks

**Comment by liderman** [comment]
Hi,
bug fixed.

The problem was in golang itself, which prohibits the use of special characters in paths. Using ":" is prohibited for Windows.
I have hidden the path fixtures from golang by transferring them to a zip archive.

**Comment by muka** [comment]
Thank you !
